# Generated by Django 4.0.2 on 2022-02-15 12:12

from django.db import migrations, models
import django.db.models.deletion
import promotion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True, verbose_name='Brand Name')),
                ('brand_logo', models.ImageField(upload_to=promotion.models.rename_brand_logo, verbose_name='Brand Logo')),
                ('brand_link', models.CharField(max_length=200, verbose_name='Brand URL')),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='Username')),
                ('comment', models.TextField(max_length=1000, verbose_name='Comment')),
                ('comment_created_on', models.DateTimeField(auto_now_add=True)),
                ('comment_last_updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-comment_last_updated_on', '-comment_created_on'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20, unique=True, verbose_name='Country Name')),
                ('country_logo', models.ImageField(upload_to=promotion.models.rename_country_logos, verbose_name='Country Logo')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=256, verbose_name='Offer Title')),
                ('offer_type', models.CharField(max_length=20, verbose_name='Offer Type')),
                ('offer_details', models.TextField(max_length=1000, verbose_name='Description')),
                ('offer_amount', models.FloatField(verbose_name='Amount')),
                ('offer_expires_on', models.DateTimeField(verbose_name='Expires On')),
                ('offer_next_available_on', models.DateTimeField(verbose_name='Next Available On')),
                ('offer_created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('offer_last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Last Updated On')),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.brand', verbose_name='Brand')),
                ('offered_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.country', verbose_name='Country')),
            ],
            options={
                'ordering': ['-offer_last_updated_on', '-offer_created_on'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='exists_in',
            field=models.ManyToManyField(to='promotion.Country', verbose_name='Countries'),
        ),
    ]
