# Generated by Django 4.0.2 on 2022-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_expires_on',
            field=models.DateField(verbose_name='Expires On'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_next_available_on',
            field=models.DateField(verbose_name='Next Available On'),
        ),
    ]
