# Generated by Django 4.0.2 on 2022-02-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_offer_offer_code_alter_brand_brand_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
