# Generated by Django 4.0.2 on 2022-02-16 05:03

from django.db import migrations, models
import promotion.models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_alter_offer_offer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.FileField(upload_to=promotion.models.rename_brand_logo, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_logo',
            field=models.FileField(upload_to=promotion.models.rename_country_logos, verbose_name='Logo'),
        ),
    ]
