# Generated by Django 4.0.2 on 2022-02-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_brand_brand_slug_country_country_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_slug',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_slug',
        ),
    ]
