# Generated by Django 4.0.2 on 2022-02-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0008_remove_brand_brand_slug_remove_country_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_code',
            field=models.CharField(default="You don't need any code!", help_text='Leave this field empty for deals.', max_length=30, verbose_name='Code'),
        ),
    ]
