# Generated by Django 4.0.2 on 2022-02-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0009_alter_offer_offer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_slug',
            field=models.SlugField(default='This is a slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_slug',
            field=models.SlugField(default='This is a slug'),
            preserve_default=False,
        ),
    ]
