# Generated by Django 4.0.2 on 2022-02-20 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_alter_brand_brand_slug_alter_country_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Amount'),
        ),
    ]
