# Generated by Django 4.0.2 on 2022-02-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0012_alter_offer_offer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
