# Generated by Django 4.0.2 on 2022-02-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0013_alter_offer_offer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_details',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
